path_classifiers:
  test:
    - "*/tests/**/*"
extraction:
  cpp:
    after_prepare:
      - mkdir ~/.conan
      - python3 -m pip install conan
      - cat /usr/local/share/ca-certificates/semmle-cache-ca/semmle-cache-ca.crt >> ~/.conan/cacert.pem
      - export CONAN_CACERT_PATH=~/.conan/cacert.pem
      - source ~/.profile
    configure:
      command:
        - mkdir build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build
    index:
      build_command:
        - cmake --build ./build -- -j4