path_classifiers:
  test:
    - "*/tests/**/*"
extraction:
  cpp:
    after_prepare:
      - python3 -m pip install conan
      - source ~/.profile
    configure:
      command:
        - mkdir build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build
    index:
      build_command:
        - cmake --build ./build -- -j4