name: 'docker'
author: 'Marcelo Pires <mpires@daitan.com>'
description: 'Daitan Digital Solutions Docker Actions'

inputs:
  context:
    description: "Docker build context"
    required: true
    default: "./"

  workspace:
    description: "Project workspace"
    required: true
    default: "/home/runner/work/pktvisor/pktvisor"

  file:
    description: "Dockerfile used to build the image"
    required: true
    default: "./Dockerfile"
  
  push:
    description: "Controls if image will be pushed to registry"
    required: true
    default: "true"

runs:
    using: 'docker'
    image: 'Dockerfile'
  