name: 'docker'
author: 'Everton Haise Taques <everton.taques@encora.com>'
description: 'Orb Community'

inputs:
  context:
    description: "Docker build context"
    required: true
    default: "./"
   
  bugsplat_key:
    description: "bugsplat key"
    required: true
    default: ""
    
  bugsplat_symbol_url:
    description: "bugsplat symbol url"
    required: true
    default: ""
   
  build_type:
    description: "build type"
    required: true
    default: "Debug"
    
  bugsplat:
    description: "bugsplat active"
    required: true
    default: "true"
    
  asan:
    description: "asan"
    required: true
    default: "ON"

  file:
    description: "Dockerfile used to build the image"
    required: true
    default: "./Dockerfile"

runs:
    using: 'docker'
    image: 'Dockerfile'
  
