name: 'docker'
author: 'Everton Haise Taques <everton.taques@encora.com>'
description: 'NS1 Labs'

inputs:
  context:
    description: "Docker build context"
    required: true
    default: "./"

  file:
    description: "Dockerfile used to build the image"
    required: true
    default: "./Dockerfile"
    
  goos:
    description: "OS for cross-build"
    required: false
    default: "linux"

runs:
    using: 'docker'
    image: 'Dockerfile'
  
