name: 'docker'
description: 'NetBox Labs Docker build go action'

inputs:
  context:
    description: "Docker build context"
    required: true
    default: "./"

  file:
    description: "Dockerfile used to build the image"
    required: true
    default: "./Dockerfile"
    
  goos:
    description: "OS for cross-build"
    required: false
    default: "linux"
    
  goarch:
    description: "ARCH for cross-build"
    required: false
    default: "amd64"

runs:
    using: 'docker'
    image: 'Dockerfile'
  
